name: My Workflow
# define events using on, manual trigger event
on: workflow_dispatch
# define jobs
jobs:
  first-job: #job name
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello"
      - name: print goodbye
        run: echo "Goodbye"
